CREATE TABLE "selection" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "selection_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" varchar(100) NOT NULL,
	"applicationId" varchar(40) NOT NULL,
	"selectionAsJson" text NOT NULL,
	"archive" varchar(10) NOT NULL,
	"ts01" varchar(10) NOT NULL,
	"selectionFidCount" integer,
	"selectionPidCount" integer,
	"bookmark" boolean NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
