CREATE TABLE "customer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customerName" varchar(50) NOT NULL,
	"street" varchar(50) NOT NULL,
	"zipCode" varchar(6) NOT NULL,
	"city" varchar(50) NOT NULL,
	"vatCode" varchar(11) NOT NULL,
	"status" boolean NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "order_header" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_header_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customerId" integer NOT NULL,
	"customerName" varchar(50) NOT NULL,
	"contactName" varchar(50) NOT NULL,
	"street" varchar(50) NOT NULL,
	"zipCode" varchar(6) NOT NULL,
	"city" varchar(50) NOT NULL,
	"vatCode" varchar(11) NOT NULL,
	"phone" varchar(20) NOT NULL,
	"status" integer DEFAULT 0,
	"applicationId" varchar(40) NOT NULL,
	"orderDescription" varchar(100) NOT NULL,
	"selectionLines" text NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "customerId" integer;--> statement-breakpoint
ALTER TABLE "order_header" ADD CONSTRAINT "order_header_customerId_customer_id_fk" FOREIGN KEY ("customerId") REFERENCES "public"."customer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user" ADD CONSTRAINT "user_customerId_customer_id_fk" FOREIGN KEY ("customerId") REFERENCES "public"."customer"("id") ON DELETE no action ON UPDATE no action;