/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteRouteImport } from './routes/_app/dashboard/route'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as ApiQlikItemsRouteImport } from './routes/api/qlik/items'
import { Route as ApiQlikAccesstokenRouteImport } from './routes/api/qlik/accesstoken'
import { Route as AppDashboardAppIdRouteImport } from './routes/_app/dashboard/$appId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const ApiQlikItemsRoute = ApiQlikItemsRouteImport.update({
  id: '/api/qlik/items',
  path: '/api/qlik/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQlikAccesstokenRoute = ApiQlikAccesstokenRouteImport.update({
  id: '/api/qlik/accesstoken',
  path: '/api/qlik/accesstoken',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardAppIdRoute = AppDashboardAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/dashboard/$appId': typeof AppDashboardAppIdRoute
  '/api/qlik/accesstoken': typeof ApiQlikAccesstokenRoute
  '/api/qlik/items': typeof ApiQlikItemsRoute
  '/admin': typeof AppAdminIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$appId': typeof AppDashboardAppIdRoute
  '/api/qlik/accesstoken': typeof ApiQlikAccesstokenRoute
  '/api/qlik/items': typeof ApiQlikItemsRoute
  '/admin': typeof AppAdminIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/_app/dashboard/$appId': typeof AppDashboardAppIdRoute
  '/api/qlik/accesstoken': typeof ApiQlikAccesstokenRoute
  '/api/qlik/items': typeof ApiQlikItemsRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/$appId'
    | '/api/qlik/accesstoken'
    | '/api/qlik/items'
    | '/admin'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/$appId'
    | '/api/qlik/accesstoken'
    | '/api/qlik/items'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/dashboard/$appId'
    | '/api/qlik/accesstoken'
    | '/api/qlik/items'
    | '/_app/admin/'
    | '/_app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiQlikAccesstokenRoute: typeof ApiQlikAccesstokenRoute
  ApiQlikItemsRoute: typeof ApiQlikItemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/qlik/items': {
      id: '/api/qlik/items'
      path: '/api/qlik/items'
      fullPath: '/api/qlik/items'
      preLoaderRoute: typeof ApiQlikItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qlik/accesstoken': {
      id: '/api/qlik/accesstoken'
      path: '/api/qlik/accesstoken'
      fullPath: '/api/qlik/accesstoken'
      preLoaderRoute: typeof ApiQlikAccesstokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/$appId': {
      id: '/_app/dashboard/$appId'
      path: '/$appId'
      fullPath: '/dashboard/$appId'
      preLoaderRoute: typeof AppDashboardAppIdRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
  }
}

interface AppDashboardRouteRouteChildren {
  AppDashboardAppIdRoute: typeof AppDashboardAppIdRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteRouteChildren: AppDashboardRouteRouteChildren = {
  AppDashboardAppIdRoute: AppDashboardAppIdRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteRouteWithChildren =
  AppDashboardRouteRoute._addFileChildren(AppDashboardRouteRouteChildren)

interface AppRouteChildren {
  AppDashboardRouteRoute: typeof AppDashboardRouteRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRouteRoute: AppDashboardRouteRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiQlikAccesstokenRoute: ApiQlikAccesstokenRoute,
  ApiQlikItemsRoute: ApiQlikItemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
